### ISSUE TITLE
Null pointer exception in 3.0.1

### ISSUE THREAD

**Issue by edlman** [marchdev-tk/cross_connectivity#10]
After upgrading to 3.0.1 I've encountered NPE in `connectivity.widget.dart` line 63 where there is `_connectivity.isConnected.valueWrapper!.value`. The valueWrapper is obviously null at the moment. I've fixed this on my local instalation by changing the code to `_connectivity.isConnected.valueWrapper?.value ?? false`.
It works fine, but I won't make a PR for this change as I'm not 100% sure this is the right solution. I hope it is. Please fix this issue either by implementing my code or other way.

**Comment by childon4god** [comment]
> After upgrading to 3.0.1 I've encountered NPE in `connectivity.widget.dart` line 63 where there is `_connectivity.isConnected.valueWrapper!.value`. The valueWrapper is obviously null at the moment. I've fixed this on my local instalation by changing the code to `_connectivity.isConnected.valueWrapper?.value ?? false`.
> It works fine, but I won't make a PR for this change as I'm not 100% sure this is the right solution. I hope it is. Please fix this issue either by implementing my code or other way.

Correct Solution

**Comment by OlehMarch** [comment]
Fixed in 3.0.2 version
