### ISSUE TITLE
Question - What you mean with "REAL Connection state"

### ISSUE THREAD

**Issue by filipenanclarez** [marchdev-tk/cross_connectivity#18]
What diference exist between you package and [connectivity_plus](https://pub.dev/packages/connectivity_plus) package?

Do you package make some ping test or another type of test to check if device is online?

What you mean with "REAL Connection state" in readme?

**Comment by dawidope** [comment]
Tired to find the answer for the same question:
https://github.com/marchdev-tk/cross_connectivity/blob/master/lib/src/core/connectivity.mixin.dart#L16
It does additional lookup for passed domain (in the code there is google.com).

**Comment by OlehMarch** [comment]
As mentioned above, this plugin uses lookup on a specified domain, by default it is google.com
This approach allows to get REAL state of the internet connection
