### ISSUE TITLE
[!] Unable to find a specification for `Reachability` depended upon by `connectivity`

### ISSUE THREAD

**Issue by liangshao-plus** [marchdev-tk/cross_connectivity#6]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by OlehMarch** [comment]
Need more info, closing this for now.
