### ISSUE TITLE
Is there any time delay for isConnected steam ?

### ISSUE THREAD

**Issue by sureace** [marchdev-tk/cross_connectivity#8]
Hi,
    Is there any time delay or interval for isConnected stream to trigger? When i turned off and turn on the wifi, it is triggering after couple of seconds.

Thanks.

**Comment by OlehMarch** [comment]
Hi,
Yes, there is a delay, by default it is 1 minute. But it is configurable via `ConnectivitySettings.init(lookupDuration: <custom duration>)`
